In [38]:
import pandas as pd

In [39]:
fund_master = pd.read_csv("01_fund_master.csv")

nav_history = pd.read_csv("02_nav_history.csv")

aum_by_fund_house = pd.read_csv("03_aum_by_fund_house.csv")

monthly_sip_inflows = pd.read_csv("04_monthly_sip_inflows.csv")

category_inflows = pd.read_csv("05_category_inflows.csv")

industry_folio_count = pd.read_csv("06_industry_folio_count.csv")

scheme_performance = pd.read_csv("07_scheme_performance.csv")

investor_transactions = pd.read_csv("08_investor_transactions.csv")

portfolio_holdings = pd.read_csv("09_portfolio_holdings.csv")

benchmark_indices = pd.read_csv("10_benchmark_indices.csv")

In [40]:
print("========== FUND MASTER ==========")

print("Shape:")
print(fund_master.shape)

print("\nFirst 5 Rows:")
display(fund_master.head())

print("\nInformation:")
fund_master.info()

print("\nMissing Values:")
print(fund_master.isnull().sum())

print("\nDuplicate Rows:")
print(fund_master.duplicated().sum())

print("\nStatistical Summary:")
display(fund_master.describe(include="all"))

print("\nUnique Fund Houses:")
print(fund_master["fund_house"].unique())

print("\nUnique Categories:")
print(fund_master["category"].unique())

print("\nUnique Sub Categories:")
print(fund_master["sub_category"].unique())

print("\nUnique Risk Categories:")
print(fund_master["risk_category"].unique())

========== FUND MASTER ==========
Shape:
(40, 15)

First 5 Rows:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

Missing Values:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
count,40.000000,40,40,40,40,40,40,40,40.000000,40.000000,40.0,40.000000,40,40,40
unique,NaN,10,40,2,12,2,34,10,NaN,NaN,NaN,NaN,29,5,9
top,NaN,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2013-01-01,NIFTY 100 TRI,NaN,NaN,NaN,NaN,Sohini Andani,Moderate,EC01
freq,NaN,5,1,34,14,32,7,14,NaN,NaN,NaN,NaN,2,16,14
mean,120247.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.237000,0.812500,500.0,1277.500000,NaN,NaN,NaN
std,14534.998667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.386584,0.387091,0.0,1082.847031,NaN,NaN,NaN
min,100016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.550000,0.000000,500.0,100.000000,NaN,NaN,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.787500,1.000000,500.0,1000.000000,NaN,NaN,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.425000,1.000000,500.0,1000.000000,NaN,NaN,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.540000,1.000000,500.0,1000.000000,NaN,NaN,NaN
max,149324.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.640000,1.000000,500.0,5000.000000,NaN,NaN,NaN

Unique Fund Houses:
['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

Unique Categories:
['Equity' 'Debt']

Unique Sub Categories:
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

Unique Risk Categories:
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [41]:
print("========== NAV HISTORY ==========")

print("Shape:")
print(nav_history.shape)

print("\nFirst 5 Rows:")
display(nav_history.head())

print("\nInformation:")
nav_history.info()

print("\nMissing Values:")
print(nav_history.isnull().sum())

print("\nDuplicate Rows:")
print(nav_history.duplicated().sum())

print("\nStatistical Summary:")
display(nav_history.describe(include="all"))

========== NAV HISTORY ==========
Shape:
(46000, 3)

First 5 Rows:

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

            amfi_code        date           nav
count    46000.000000       46000  46000.000000
unique            NaN        1150           NaN
top               NaN  2026-05-29           NaN
freq              NaN          40           NaN
mean    120247.000000         NaN    269.570265
std      14352.317221         NaN    577.187060
min     100016.000000         NaN     26.136600
25%     118632.750000         NaN     69.170425
50%     119551.500000         NaN    122.732150
75%     120842.250000         NaN    260.338675
max     149324.000000         NaN   4268.549700

In [42]:
print("========== AUM BY FUND HOUSE ==========")

print("Shape:")
print(aum_by_fund_house.shape)

print("\nFirst 5 Rows:")
display(aum_by_fund_house.head())

print("\nInformation:")
aum_by_fund_house.info()

print("\nMissing Values:")
print(aum_by_fund_house.isnull().sum())

print("\nDuplicate Rows:")
print(aum_by_fund_house.duplicated().sum())

print("\nStatistical Summary:")
display(aum_by_fund_house.describe(include="all"))

========== AUM BY FUND HOUSE ==========
Shape:
(90, 5)

First 5 Rows:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

Missing Values:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

              date       fund_house  aum_lakh_crore     aum_crore  num_schemes
count           90               90       90.000000  9.000000e+01    90.000000
unique           9               10             NaN           NaN          NaN
top     2022-03-31  SBI Mutual Fund             NaN           NaN          NaN
freq            10                9             NaN           NaN          NaN
mean           NaN              NaN        4.352889  4.352889e+05   152.200000
std            NaN              NaN        2.734328  2.734328e+05    52.108832
min            NaN              NaN        1.050000  1.050000e+05    56.000000
25%            NaN              NaN        2.525000  2.525000e+05    95.000000
50%            NaN              NaN        3.450000  3.450000e+05   172.500000
75%            NaN              NaN        5.675000  5.675000e+05   195.000000
max            NaN              NaN       12.500000  1.250000e+06   216.000000

In [43]:
print("========== MONTHLY SIP INFLOWS ==========")

print("Shape:")
print(monthly_sip_inflows.shape)

print("\nFirst 5 Rows:")
display(monthly_sip_inflows.head())

print("\nInformation:")
monthly_sip_inflows.info()

print("\nMissing Values:")
print(monthly_sip_inflows.isnull().sum())

print("\nDuplicate Rows:")
print(monthly_sip_inflows.duplicated().sum())

print("\nStatistical Summary:")
display(monthly_sip_inflows.describe(include="all"))

========== MONTHLY SIP INFLOWS ==========
Shape:
(48, 6)

First 5 Rows:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

Missing Values:
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
count,48,48.000000,48.000000,48.000000,48.000000,36.000000
unique,48,NaN,NaN,NaN,NaN,NaN
top,2022-01,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,19577.520833,7.189583,9.893750,8.632083,31.456944
std,NaN,6354.329621,1.271457,5.370745,3.613579,11.768190
min,NaN,11438.000000,4.910000,7.500000,4.800000,15.800000
25%,NaN,13658.500000,6.110000,8.775000,5.790000,20.245000
50%,NaN,18224.000000,7.150000,9.200000,7.265000,28.295000
75%,NaN,25944.250000,8.300000,9.562500,10.525000,40.807500
max,NaN,31002.000000,9.350000,46.000000,15.900000,53.050000

In [44]:
print("========== CATEGORY INFLOWS ==========")

print("Shape:")
print(category_inflows.shape)

print("\nFirst 5 Rows:")
display(category_inflows.head())

print("\nInformation:")
category_inflows.info()

print("\nMissing Values:")
print(category_inflows.isnull().sum())

print("\nDuplicate Rows:")
print(category_inflows.duplicated().sum())

print("\nStatistical Summary:")
display(category_inflows.describe(include="all"))

========== CATEGORY INFLOWS ==========
Shape:
(144, 3)

First 5 Rows:

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

Missing Values:
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

          month   category  net_inflow_crore
count       144        144        144.000000
unique       12         12               NaN
top     2024-04  Large Cap               NaN
freq         12         12               NaN
mean        NaN        NaN       6473.881944
std         NaN        NaN       9718.335947
min         NaN        NaN        437.000000
25%         NaN        NaN       1801.250000
50%         NaN        NaN       4148.000000
75%         NaN        NaN       5304.000000
max         NaN        NaN      41952.000000

In [45]:
print("========== INDUSTRY FOLIO COUNT ==========")

print("Shape:")
print(industry_folio_count.shape)

print("\nFirst 5 Rows:")
display(industry_folio_count.head())

print("\nInformation:")
industry_folio_count.info()

print("\nMissing Values:")
print(industry_folio_count.isnull().sum())

print("\nDuplicate Rows:")
print(industry_folio_count.duplicated().sum())

print("\nStatistical Summary:")
display(industry_folio_count.describe(include="all"))

========== INDUSTRY FOLIO COUNT ==========
Shape:
(21, 6)

First 5 Rows:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

Missing Values:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
count,21,21.000000,21.000000,21.000000,21.000000,21.000000
unique,21,NaN,NaN,NaN,NaN,NaN
top,2022-01,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,19.829524,13.880476,2.776190,1.190000,1.983333
std,NaN,4.583376,3.207799,0.640308,0.274864,0.459079
min,NaN,13.260000,9.280000,1.860000,0.800000,1.330000
25%,NaN,15.540000,10.880000,2.180000,0.930000,1.550000
50%,NaN,19.980000,13.990000,2.800000,1.200000,2.000000
75%,NaN,23.890000,16.720000,3.340000,1.430000,2.390000
max,NaN,26.120000,18.280000,3.660000,1.570000,2.610000

In [46]:
print("========== SCHEME PERFORMANCE ==========")

print("Shape:")
print(scheme_performance.shape)

print("\nFirst 5 Rows:")
display(scheme_performance.head())

print("\nInformation:")
scheme_performance.info()

print("\nMissing Values:")
print(scheme_performance.isnull().sum())

print("\nDuplicate Rows:")
print(scheme_performance.duplicated().sum())

print("\nStatistical Summary:")
display(scheme_performance.describe(include="all"))

========== SCHEME PERFORMANCE ==========
Shape:
(40, 19)

First 5 Rows:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
count,40.000000,40,40,40,40,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000,40
unique,NaN,40,10,12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
top,NaN,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate
freq,NaN,1,5,14,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
mean,120247.000000,NaN,NaN,NaN,NaN,14.376000,14.089000,14.516750,12.835500,1.253500,0.873250,1.361750,2.082500,14.962500,-19.200250,26091.60000,1.237000,4.250000,NaN
std,14534.998667,NaN,NaN,NaN,NaN,4.883023,4.617253,4.454021,4.740972,0.447412,0.224846,1.475805,2.203144,6.669282,8.819164,13809.11134,0.386584,0.742484,NaN
min,100016.000000,NaN,NaN,NaN,NaN,4.260000,5.140000,5.430000,3.960000,0.510000,0.220000,0.800000,1.030000,0.500000,-33.500000,979.00000,0.550000,3.000000,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,11.735000,12.035000,12.340000,10.690000,0.887500,0.890000,0.865000,1.270000,14.000000,-25.062500,17400.50000,0.787500,4.000000,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,14.620000,14.205000,14.185000,13.090000,1.205000,0.960000,0.925000,1.445000,14.000000,-20.600000,26713.00000,1.425000,4.000000,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,16.392500,15.882500,17.585000,14.775000,1.700000,1.000000,0.985000,1.637500,19.000000,-14.255000,38125.00000,1.540000,5.000000,NaN
max,149324.000000,NaN,NaN,NaN,NaN,24.930000,23.390000,23.800000,22.160000,1.980000,1.040000,7.680000,10.370000,25.000000,-2.230000,49046.00000,1.640000,5.000000,NaN

In [47]:
print("========== INVESTOR TRANSACTIONS ==========")

print("Shape:")
print(investor_transactions.shape)

print("\nFirst 5 Rows:")
display(investor_transactions.head())

print("\nInformation:")
investor_transactions.info()

print("\nMissing Values:")
print(investor_transactions.isnull().sum())

print("\nDuplicate Rows:")
print(investor_transactions.duplicated().sum())

print("\nStatistical Summary:")
display(investor_transactions.describe(include="all"))

========== INVESTOR TRANSACTIONS ==========
Shape:
(32778, 13)

First 5 Rows:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
count,32778,32778,32778.000000,32778,32778.000000,32778,32778,32778,32778,32778,32778.000000,32778,32778
unique,5000,516,NaN,3,NaN,12,24,2,5,2,NaN,4,2
top,INV001497,2025-04-28,NaN,SIP,NaN,Punjab,Kolkata,T30,26-35,Male,NaN,Net Banking,Verified
freq,12,88,NaN,19716,NaN,2965,2748,21719,13463,21809,NaN,8250,30146
mean,NaN,NaN,120264.617518,NaN,107437.318628,NaN,NaN,NaN,NaN,NaN,26.181219,NaN,NaN
std,NaN,NaN,14370.205345,NaN,150415.905084,NaN,NaN,NaN,NaN,NaN,20.805425,NaN,NaN
min,NaN,NaN,100016.000000,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN
25%,NaN,NaN,118632.000000,NaN,3153.000000,NaN,NaN,NaN,NaN,NaN,10.600000,NaN,NaN
50%,NaN,NaN,119551.000000,NaN,17782.500000,NaN,NaN,NaN,NaN,NaN,19.700000,NaN,NaN
75%,NaN,NaN,120843.000000,NaN,189324.250000,NaN,NaN,NaN,NaN,NaN,37.400000,NaN,NaN
max,NaN,NaN,149324.000000,NaN,597498.000000,NaN,NaN,NaN,NaN,NaN,99.700000,NaN,NaN

In [48]:
print("========== PORTFOLIO HOLDINGS ==========")

print("Shape:")
print(portfolio_holdings.shape)

print("\nFirst 5 Rows:")
display(portfolio_holdings.head())

print("\nInformation:")
portfolio_holdings.info()

print("\nMissing Values:")
print(portfolio_holdings.isnull().sum())

print("\nDuplicate Rows:")
print(portfolio_holdings.duplicated().sum())

print("\nStatistical Summary:")
display(portfolio_holdings.describe(include="all"))

========== PORTFOLIO HOLDINGS ==========
Shape:
(322, 8)

First 5 Rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 20.3+ KB

Missing Values:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
count,322.000000,322,322,322,322.000000,322.000000,322.000000,322
unique,NaN,30,30,14,NaN,NaN,NaN,1
top,NaN,BHARTIARTL,Bharti Airtel Ltd,Banking,NaN,NaN,NaN,2025-12-31
freq,NaN,15,15,60,NaN,NaN,NaN,322
mean,121210.434783,NaN,NaN,NaN,10.558975,1008.846646,4080.870528,NaN
std,14669.377920,NaN,NaN,NaN,6.060137,543.827535,2265.186353,NaN
min,100016.000000,NaN,NaN,NaN,0.990000,55.740000,246.780000,NaN
25%,118633.000000,NaN,NaN,NaN,6.015000,513.702500,2081.985000,NaN
50%,119552.000000,NaN,NaN,NaN,9.395000,1045.670000,4138.995000,NaN
75%,120842.750000,NaN,NaN,NaN,13.917500,1477.502500,5914.307500,NaN
max,149324.000000,NaN,NaN,NaN,38.180000,1999.500000,7942.960000,NaN

In [49]:
print("========== BENCHMARK INDICES ==========")

print("Shape:")
print(benchmark_indices.shape)

print("\nFirst 5 Rows:")
display(benchmark_indices.head())

print("\nInformation:")
benchmark_indices.info()

print("\nMissing Values:")
print(benchmark_indices.isnull().sum())

print("\nDuplicate Rows:")
print(benchmark_indices.duplicated().sum())

print("\nStatistical Summary:")
display(benchmark_indices.describe(include="all"))

========== BENCHMARK INDICES ==========
Shape:
(8050, 3)

First 5 Rows:

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

Missing Values:
date           0
index_name     0
close_value    0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

              date index_name   close_value
count         8050       8050   8050.000000
unique        1150          7           NaN
top     2026-05-29    NIFTY50           NaN
freq             7       1150           NaN
mean           NaN        NaN  18351.950181
std            NaN        NaN  14169.995121
min            NaN        NaN   1444.130000
25%            NaN        NaN   2819.062500
50%            NaN        NaN  18392.960000
75%            NaN        NaN  26539.097500
max            NaN        NaN  79075.390000